# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
# docker-compose -f ./docker-compose.yml up -d
# docker-compose -f ./docker-compose.yml down -d
# docker ps -q --> command to list the IDs of all running containers

version: "3"
services:
   hub:
      image: selenium/hub:4.18.1-20240224
      ports:
      - 4444:4444
    # - 4442:4442
    # - 4443:4443
   chrome:
      image: selenium/node-chrome:4.18.1-20240224
      shm_size: 2g
      depends_on:
      - hub
      environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
   edge:
      image: selenium/node-edge:4.18.1-20240224
      shm_size: 2g
      depends_on:
      - hub
      environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1